# Generated by Django 4.1.3 on 2022-12-03 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogTable',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='Screenshot (3).png', null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, default='Screenshot (3).png', null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default='Screenshot (3).png', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactUsersTable',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
